### ISSUE TITLE
Milestone 2 Tasks

### ISSUE THREAD

**Issue by Anahita97** [UBC-MDS/Daily_Rainfall_Over_NSW_Group4#14]
1. Setup your EC2 instance
- [x] Attach a [screen shot](https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone2/image/1_result.png).
2. Setup your JupyterHub
- [x] Attach a [screen shot](https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone2/image/2_result.png) with all the group members in it.
3. Setup the server
- [x] Add your team members to EC2 instance.
- [x] Setup a common data folder accessible by all users in the JupyterHub.
- [x] Install and configure AWS CLI.
- [x] Make sure you mask the IP address.
- [x] Attach a [screen shot](https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone2/image/3_result.png).
4. Get the data
- [x] Get the data we wrangled in the first milestone.
5. Setup the S3 bucket and move data
- [x] Create a bucket with the name format of mds-s3-xxx.
- [x] Create folder called "output".
- [x] Move the "observed_daily_rainfall_SYD.csv" file from the Milestone1 data folder to your s3 bucket from your local computer.
- [x] Move "combined_model_data_parti.parquet" in step 4 to S3 using the cli.
- [x] Attach a [screen shot](https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone2/image/4_result.png) showing 3 objects.
6. Wrangle data
- [x] Get "combined_model_data_parti.parquet" and "observed_daily_rainfall_SYD.csv" from S3.
- [x] Query Sydney data and drop latitude and longitude columns. Expected shape (1150049, 2).
- [x] Add "observed_daily_rainfall_SYD.csv" as a column named "Observed".
- [x] Wrangle the data into the given format. Expected shape (46020, 26).
- [x] Save the processed file to S3 as CSV.

**Comment by LukeAC** [comment]
Here are all screenshots excluding the data-wrangling screenshot.

1. **EC2-setup**
<img width="470" alt="EC2-instance" src="https://user-images.githubusercontent.com/75291170/162336462-9ae97f74-6f9b-48a7-9a5b-c232a17e2572.png">

2. **jupyter-hub-setup**
<img width="767" alt="jupyter-hub-setup" src="https://user-images.githubusercontent.com/75291170/162336715-aac0672b-193d-4015-a307-89f1031ddaa8.png">


3.  **S3-bucket-setup**
<img width="692" alt="S3-bucket-setup" src="https://user-images.githubusercontent.com/75291170/162336466-1fc04cd9-f0be-4b56-b8c5-9e697de0c0e0.png">

4. **server-setup**
<img width="442" alt="server-setup" src="https://user-images.githubusercontent.com/60054000/162357327-b63d14ee-82f9-4bc6-9e2f-28b487e326c5.png">

**Comment by LukeAC** [comment]
New EC2-setup img:

<img width="755" alt="EC2-instance" src="https://user-images.githubusercontent.com/60054000/162357223-a954665e-e0e4-448d-8940-265d51c0cfed.png">
