### ISSUE TITLE
Milestone 3 Tasks

### ISSUE THREAD

**Issue by Anahita97** [UBC-MDS/Daily_Rainfall_Over_NSW_Group4#17]
1. Setup your EMR cluster
- [x] Attach the [screen shot](https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone3/images/Task1.png).
2. Setup your browser, jupyter environment and connect to the master node 
- [x] Attach the [screen shot](https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone3/images/Task2.png).
3. Develop a Ml model 
- [x] Complete [Milestone3-Task3.ipynb](https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone3/Milestone3-Task3.ipynb) 
- [x] Upload to JupyterHub.
4. Obtain best hyperparameter settings using spark's MLlib
- [x] Complete [Milestone3-Task4.ipynb](https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone3/Milestone3-Task4.ipynb)
- [x] Upload to JupyterHub.
5. Submission instructions
- [x] Python 3 notebook, with the code for ML model in scikit-learn (Milestone3-Task3.ipynb).
- [x] PySpark notebook, with the code for obtaining the best hyperparameter settings (Milestone3-Task4.ipynb).
- [x] Screenshots:
- Setup for EMR cluster.
- Setup your browser, jupyter environment & connect to the master node.
- Your S3 bucket showing model.joblib file (From Task 3 Develop a ML model using scikit-learn)

**Comment by stevenlio88** [comment]
![image](https://user-images.githubusercontent.com/78633001/163491687-2cd5c807-f7a2-4f31-8805-4bb8755e74c4.png)
![task1-screenshot](https://user-images.githubusercontent.com/78633001/163491688-492a9062-1486-4d9a-a833-1d665d08fe62.png)
![task4-screenshot](https://user-images.githubusercontent.com/78633001/163491690-31c1f6da-6d2f-4e9b-9c85-8148250d49a2.png)
