### ISSUE TITLE
Milestone 4 Tasks

### ISSUE THREAD

**Issue by Anahita97** [UBC-MDS/Daily_Rainfall_Over_NSW_Group4#22]
1. Develop your API
- [x] Create an endpoint that accepts a POST request of the 25 features.
- [x] Process data, make prediction and return the prediction.

2. Deploy the API
- [x] Setup an EC2 instance. Make sure you add a rule in security groups to accept All TCP connections from Anywhere.
- [x] Make a file app.py file in your instance and copy what you developed above.
- [x] Download your model from s3 to your EC2 instance.
- [x] Install dependencies.
- [x] Create a new screen session, and within that session, start up your flask app.
3. Summarize your journey
- [x] Milestone 1 to Milestone 4
4. Submission instructions
- [x] Milestone 4 notebook with solution to 1 & 3.
- [x] [Screenshot](https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone4/images/curl_deploy_sample.png) from output after trying curl.

**Comment by stevenlio88** [comment]
![milestone-4](https://user-images.githubusercontent.com/78633001/164603039-753c7603-84c9-49e1-8d77-ebf6e1541347.png)

**Comment by stevenlio88** [comment]
Milestone 4 completed see [release](https://github.com/UBC-MDS/Daily_Rainfall_Over_NSW_Group4/releases/tag/milestone-4).
