### ISSUE TITLE
Milestone 1 tasks

### ISSUE THREAD

**Issue by Anahita97** [UBC-MDS/Daily_Rainfall_Over_NSW_Group4#5]
**1. Team-work contract**
- [x] Create team-work contract.

**2. Create repository and project structure**
- [x] Brief introduction of the project in the README.
- [x] Create a folder called notebooks.

**3. Downloading the data**
- [x] Download the data using figshare API.
- [x] Extract the zip file.

**4. Combining data CSVs**
- [x] Combine the CSVs into a single CSV.
- [x] Add an extra column called model.
- [x] Compare run time.

**5. Load the combined CSV to memory and perform a simple EDA**
- [x] Investigate at least two of the approaches to reduce memory usage while performing the EDA.
- [x] Compare run time.

**6. Perform simple EDA in R**
- [x] Transfer dataframe from python to R.
- [x] Discuss why you chose this approach.

**Specific Expectations:**
- [x] A well-documented and self-explanatory notebook exploring different options to tackle big data.
- [x] Discuss any challenges or difficulties you faced when dealing with this large amount of data on your laptops. Briefly explain your approach to overcome the challenges or reasons why you could not overcome them.

**Comment by LukeAC** [comment]
I'll take a look at and update the env yaml file.

**Comment by stevenlio88** [comment]
I will finish up part 6 of the notebook (add parquet analysis + discussion) - aim to be done tonight

**Comment by Anahita97** [comment]
I will clean up the notebook and add narration to notebook.
